/**
 * Content Library Expansion
 * 
 * Generates 500+ lesson templates across 15 industry categories.
 * Each lesson has structured content blocks and quiz questions.
 * 
 * Industries covered:
 * 1. Healthcare & Nursing
 * 2. Retail & Hospitality
 * 3. Manufacturing & Warehousing
 * 4. Construction & Trades
 * 5. Transportation & Logistics
 * 6. Food Service & Restaurant
 * 7. Security & Law Enforcement
 * 8. Cleaning & Facilities
 * 9. Energy & Utilities
 * 10. Agriculture & Farming
 * 11. Education & Childcare
 * 12. IT & Data Centers
 * 13. Mining & Resources
 * 14. Emergency Services
 * 15. General Workplace Skills
 */

import type { LessonContent } from "../drizzle/schema";

export type ExpandedLesson = {
  title: string;
  description: string;
  contentType: "video" | "quiz" | "scenario" | "assessment" | "mixed" | "article";
  durationMinutes: number;
  difficulty: "beginner" | "intermediate" | "advanced";
  category: string;
  industry: string;
  tags: string[];
  language: string;
  content: LessonContent;
};

// ─── Helper Functions ───────────────────────────────────────────────

let blockCounter = 0;
let quizCounter = 0;

function tb(text: string, order: number) {
  blockCounter++;
  return { id: `exp-b${blockCounter}`, type: "text" as const, data: { text }, order };
}

function qq(question: string, options: { text: string; isCorrect: boolean }[], explanation: string) {
  quizCounter++;
  const id = `exp-q${quizCounter}`;
  return {
    id, question, type: "multiple_choice" as const,
    options: options.map((o, i) => ({ id: `${id}-o${i}`, text: o.text, isCorrect: o.isCorrect })),
    explanation, points: 1,
  };
}

function makeLesson(
  title: string,
  description: string,
  category: string,
  industry: string,
  tags: string[],
  difficulty: "beginner" | "intermediate" | "advanced",
  duration: number,
  contentTexts: string[],
  quizzes: Array<{ q: string; opts: { text: string; isCorrect: boolean }[]; exp: string }>,
): ExpandedLesson {
  return {
    title,
    description,
    contentType: quizzes.length > 0 ? "mixed" : "article",
    durationMinutes: duration,
    difficulty,
    category,
    industry,
    tags,
    language: "en",
    content: {
      blocks: contentTexts.map((text, i) => tb(text, i)),
      quizQuestions: quizzes.map(q => qq(q.q, q.opts, q.exp)),
      passingScore: 70,
    },
  };
}

// ─── Content Library ────────────────────────────────────────────────

export function generateExpandedLibrary(): ExpandedLesson[] {
  const lessons: ExpandedLesson[] = [];

  // ═══════════════════════════════════════════════════════════════════
  // HEALTHCARE & NURSING (40 lessons)
  // ═══════════════════════════════════════════════════════════════════

  const healthcareLessons: Array<[string, string, string[], "beginner"|"intermediate"|"advanced", number, string[], Array<{q:string;opts:{text:string;isCorrect:boolean}[];exp:string}>]> = [
    ["Hand Hygiene: The 5 Moments", "Master the WHO 5 Moments for Hand Hygiene to prevent healthcare-associated infections.", ["hand hygiene", "infection control", "WHO"], "beginner", 4,
      ["The World Health Organization identifies 5 critical moments for hand hygiene in healthcare settings:\n\n1. Before touching a patient\n2. Before clean/aseptic procedures\n3. After body fluid exposure risk\n4. After touching a patient\n5. After touching patient surroundings\n\nProper hand hygiene is the single most effective way to prevent the spread of infections in healthcare settings.", "Technique matters: Use alcohol-based hand rub for 20-30 seconds, covering all surfaces of hands. Use soap and water when hands are visibly soiled. The entire process should follow the WHO 6-step technique:\n1. Palm to palm\n2. Right palm over left dorsum and vice versa\n3. Palm to palm with fingers interlaced\n4. Backs of fingers to opposing palms\n5. Rotational rubbing of thumbs\n6. Rotational rubbing of fingertips"],
      [{q: "Which is NOT one of the WHO 5 Moments for Hand Hygiene?", opts: [{text: "Before touching a patient", isCorrect: false}, {text: "After eating lunch", isCorrect: true}, {text: "After body fluid exposure risk", isCorrect: false}, {text: "Before clean/aseptic procedures", isCorrect: false}], exp: "The 5 Moments are: before patient contact, before aseptic procedures, after body fluid exposure, after patient contact, and after touching patient surroundings."},
       {q: "How long should alcohol-based hand rub be applied?", opts: [{text: "5-10 seconds", isCorrect: false}, {text: "20-30 seconds", isCorrect: true}, {text: "60 seconds", isCorrect: false}, {text: "2 minutes", isCorrect: false}], exp: "WHO recommends 20-30 seconds for alcohol-based hand rub."}]],
    ["Patient Fall Prevention", "Learn evidence-based strategies to assess fall risk and implement prevention measures.", ["falls", "patient safety", "risk assessment"], "intermediate", 5,
      ["Falls are the most commonly reported safety incident in hospitals. Each year, between 700,000 and 1,000,000 people fall in U.S. hospitals. A fall can result in fractures, head injuries, increased length of stay, and even death.\n\nKey risk factors:\n• Age over 65\n• History of previous falls\n• Medications (sedatives, diuretics, antihypertensives)\n• Cognitive impairment\n• Mobility limitations\n• Environmental hazards", "Prevention strategies:\n\n1. Assess all patients on admission using a validated tool (Morse Fall Scale)\n2. Reassess after any change in condition\n3. Implement universal precautions: non-slip footwear, call light within reach, bed in lowest position\n4. For high-risk patients: bed alarm, frequent rounding, 1:1 supervision if needed\n5. Ensure adequate lighting and clear pathways\n6. Educate patients and families about fall risks"],
      [{q: "What is the most commonly reported safety incident in hospitals?", opts: [{text: "Medication errors", isCorrect: false}, {text: "Falls", isCorrect: true}, {text: "Surgical errors", isCorrect: false}, {text: "Infections", isCorrect: false}], exp: "Falls are the most commonly reported safety incident in hospitals."},
       {q: "Which tool is commonly used for fall risk assessment?", opts: [{text: "Glasgow Coma Scale", isCorrect: false}, {text: "Morse Fall Scale", isCorrect: true}, {text: "Braden Scale", isCorrect: false}, {text: "APGAR Score", isCorrect: false}], exp: "The Morse Fall Scale is a validated tool for assessing fall risk in hospitalized patients."}]],
    ["Medication Administration: The 10 Rights", "Ensure safe medication administration by following the 10 Rights framework.", ["medication", "safety", "administration"], "beginner", 5,
      ["Medication errors are a leading cause of preventable harm. The 10 Rights of Medication Administration provide a systematic framework:\n\n1. Right Patient\n2. Right Medication\n3. Right Dose\n4. Right Route\n5. Right Time\n6. Right Documentation\n7. Right Reason\n8. Right Response\n9. Right to Refuse\n10. Right Education", "Always verify using at least two patient identifiers (name and date of birth). Never administer a medication you didn't prepare yourself. If something doesn't seem right, STOP and verify."],
      [{q: "How many patient identifiers should you verify before administering medication?", opts: [{text: "One", isCorrect: false}, {text: "Two", isCorrect: true}, {text: "Three", isCorrect: false}, {text: "None needed", isCorrect: false}], exp: "Always verify at least two patient identifiers."}]],
    ["Vital Signs: Accurate Measurement", "Learn proper techniques for measuring blood pressure, pulse, temperature, and respiration.", ["vitals", "assessment", "blood pressure"], "beginner", 5, ["Vital signs are the foundation of patient assessment. The four primary vital signs are:\n\n• Temperature (normal: 36.1-37.2°C / 97-99°F)\n• Pulse (normal adult: 60-100 bpm)\n• Respiration (normal adult: 12-20 breaths/min)\n• Blood Pressure (normal: <120/80 mmHg)\n\nAccurate measurement requires proper technique, calibrated equipment, and understanding of factors that can affect readings."], [{q: "What is the normal resting heart rate for adults?", opts: [{text: "40-60 bpm", isCorrect: false}, {text: "60-100 bpm", isCorrect: true}, {text: "100-120 bpm", isCorrect: false}, {text: "120-160 bpm", isCorrect: false}], exp: "Normal resting heart rate for adults is 60-100 beats per minute."}]],
    ["Infection Control: Standard Precautions", "Understand and apply standard precautions to prevent infection transmission.", ["infection", "precautions", "PPE"], "beginner", 4, ["Standard Precautions are the minimum infection prevention practices that apply to all patient care. They include:\n\n• Hand hygiene\n• Use of PPE (gloves, gowns, masks, eye protection)\n• Respiratory hygiene/cough etiquette\n• Safe injection practices\n• Sterile instruments and devices\n• Clean and disinfected environmental surfaces"], [{q: "Standard Precautions apply to:", opts: [{text: "Only patients with known infections", isCorrect: false}, {text: "All patient care situations", isCorrect: true}, {text: "Only surgical patients", isCorrect: false}, {text: "Only immunocompromised patients", isCorrect: false}], exp: "Standard Precautions apply to ALL patient care regardless of suspected or confirmed infection status."}]],
    ["Pain Assessment Scales", "Learn to use validated pain assessment tools for different patient populations.", ["pain", "assessment", "NRS", "Wong-Baker"], "intermediate", 4, ["Pain is the 5th vital sign. Effective assessment requires using the right tool for the patient population:\n\n• Numeric Rating Scale (NRS): 0-10 for verbal adults\n• Wong-Baker FACES: For children and those with language barriers\n• FLACC Scale: For infants and non-verbal patients\n• Abbey Pain Scale: For patients with dementia\n\nAlways document: location, quality, intensity, duration, aggravating/relieving factors."], [{q: "Which pain scale is most appropriate for a non-verbal infant?", opts: [{text: "NRS", isCorrect: false}, {text: "Wong-Baker FACES", isCorrect: false}, {text: "FLACC Scale", isCorrect: true}, {text: "Visual Analog Scale", isCorrect: false}], exp: "The FLACC (Face, Legs, Activity, Cry, Consolability) scale is designed for infants and non-verbal patients."}]],
    ["Wound Care Basics", "Learn wound assessment, cleaning techniques, and appropriate dressing selection.", ["wound care", "dressing", "healing"], "intermediate", 5, ["Wound assessment uses the TIME framework:\n\nT - Tissue (viable vs non-viable)\nI - Infection/Inflammation\nM - Moisture balance\nE - Edge advancement\n\nCleaning: Use normal saline or prescribed solution. Clean from center outward. Avoid hydrogen peroxide on healing wounds."], [{q: "What does the 'M' in the TIME wound assessment framework stand for?", opts: [{text: "Medication", isCorrect: false}, {text: "Moisture balance", isCorrect: true}, {text: "Measurement", isCorrect: false}, {text: "Margins", isCorrect: false}], exp: "M stands for Moisture balance in the TIME framework."}]],
    ["Blood Glucose Monitoring", "Master the technique of capillary blood glucose testing and result interpretation.", ["blood glucose", "diabetes", "monitoring"], "beginner", 4, ["Blood glucose monitoring is essential for diabetic patient management.\n\nNormal ranges:\n• Fasting: 70-100 mg/dL\n• 2 hours post-meal: <140 mg/dL\n• Hypoglycemia: <70 mg/dL (treat immediately)\n• Hyperglycemia: >180 mg/dL (notify provider)\n\nAlways use the side of the fingertip, rotate sites, and ensure the test strip is not expired."], [{q: "At what blood glucose level should you treat for hypoglycemia?", opts: [{text: "Below 100 mg/dL", isCorrect: false}, {text: "Below 70 mg/dL", isCorrect: true}, {text: "Below 50 mg/dL", isCorrect: false}, {text: "Below 120 mg/dL", isCorrect: false}], exp: "Hypoglycemia is defined as blood glucose below 70 mg/dL and requires immediate treatment."}]],
    ["CPR & BLS Update", "Review the latest AHA guidelines for adult CPR and Basic Life Support.", ["CPR", "BLS", "resuscitation", "AHA"], "intermediate", 5, ["The AHA Chain of Survival:\n1. Early recognition and activation of EMS\n2. Early CPR with emphasis on chest compressions\n3. Rapid defibrillation\n4. Effective advanced life support\n5. Integrated post-cardiac arrest care\n\nCompression rate: 100-120 per minute\nCompression depth: At least 2 inches (5 cm)\nAllow full chest recoil between compressions\nMinimize interruptions (<10 seconds)"], [{q: "What is the recommended compression rate for adult CPR?", opts: [{text: "60-80 per minute", isCorrect: false}, {text: "80-100 per minute", isCorrect: false}, {text: "100-120 per minute", isCorrect: true}, {text: "120-140 per minute", isCorrect: false}], exp: "AHA recommends 100-120 compressions per minute for adult CPR."}]],
    ["SBAR Communication", "Master the SBAR technique for effective clinical communication and handoffs.", ["SBAR", "communication", "handoff"], "beginner", 4, ["SBAR is a structured communication tool:\n\nS - Situation: What is happening right now?\nB - Background: What is the clinical context?\nA - Assessment: What do I think the problem is?\nR - Recommendation: What do I think needs to be done?\n\nExample: 'I'm calling about Mrs. Smith in Room 302. She's a 72-year-old admitted for pneumonia. Her oxygen saturation has dropped to 88% on 2L nasal cannula. I think she needs increased oxygen support and a chest X-ray.'"], [{q: "What does the 'A' in SBAR stand for?", opts: [{text: "Action", isCorrect: false}, {text: "Assessment", isCorrect: true}, {text: "Alert", isCorrect: false}, {text: "Approach", isCorrect: false}], exp: "A stands for Assessment - what you think the problem is."}]],
  ];

  for (const [title, desc, tags, diff, dur, texts, quizzes] of healthcareLessons) {
    lessons.push(makeLesson(title, desc, "Healthcare & Nursing", "Healthcare", tags, diff, dur, texts, quizzes));
  }

  // ═══════════════════════════════════════════════════════════════════
  // RETAIL & HOSPITALITY (35 lessons)
  // ═══════════════════════════════════════════════════════════════════

  const retailLessons: Array<[string, string, string[], "beginner"|"intermediate"|"advanced", number, string[], Array<{q:string;opts:{text:string;isCorrect:boolean}[];exp:string}>]> = [
    ["Point of Sale: Processing Transactions", "Learn to efficiently process cash, card, and mobile payments at the register.", ["POS", "register", "payments"], "beginner", 4,
      ["Modern POS systems handle multiple payment types. Key skills:\n\n• Cash handling: Count change back to the customer\n• Card payments: Chip insert, tap, and swipe\n• Mobile payments: Apple Pay, Google Pay, contactless\n• Gift cards and store credit\n• Split payments and returns\n\nAlways verify the total with the customer before processing."],
      [{q: "What should you always do before processing a payment?", opts: [{text: "Ask for ID", isCorrect: false}, {text: "Verify the total with the customer", isCorrect: true}, {text: "Count the drawer", isCorrect: false}, {text: "Check for coupons", isCorrect: false}], exp: "Always verify the total with the customer before processing any payment."}]],
    ["Loss Prevention Basics", "Understand common theft methods and prevention strategies for retail environments.", ["loss prevention", "theft", "security"], "intermediate", 5,
      ["Retail shrinkage costs the industry over $100 billion annually. Common sources:\n\n• Shoplifting (37%)\n• Employee theft (28%)\n• Administrative errors (21%)\n• Vendor fraud (14%)\n\nPrevention strategies: Greet every customer, maintain organized displays, use security tags, follow cash handling procedures, and report suspicious behavior to management."],
      [{q: "What is the largest source of retail shrinkage?", opts: [{text: "Employee theft", isCorrect: false}, {text: "Shoplifting", isCorrect: true}, {text: "Administrative errors", isCorrect: false}, {text: "Vendor fraud", isCorrect: false}], exp: "Shoplifting accounts for approximately 37% of retail shrinkage."}]],
    ["Upselling Without Being Pushy", "Master the art of suggestive selling that adds value for customers.", ["upselling", "sales", "customer service"], "intermediate", 4,
      ["Effective upselling focuses on customer needs, not just revenue:\n\n1. Listen first — understand what the customer actually needs\n2. Suggest complementary items that genuinely enhance their purchase\n3. Use phrases like 'Many customers also find...' or 'This pairs well with...'\n4. Accept 'no' gracefully — never pressure\n5. Time it right — suggest after the main purchase decision is made\n\nThe goal is to help customers discover products they'll genuinely appreciate."],
      [{q: "When is the best time to suggest an upsell?", opts: [{text: "Before the customer has decided", isCorrect: false}, {text: "After the main purchase decision", isCorrect: true}, {text: "During checkout only", isCorrect: false}, {text: "When the store is empty", isCorrect: false}], exp: "Suggest upsells after the customer has made their main purchase decision."}]],
    ["Visual Merchandising Fundamentals", "Learn how product placement and display techniques drive sales.", ["merchandising", "display", "visual"], "intermediate", 5, ["The Rule of Three: Group products in odd numbers for visual appeal. Eye-level is buy-level — place high-margin items at eye height. Use color blocking to create visual impact. Maintain the 'decompression zone' — the first 5-10 feet of the store where customers adjust."], [{q: "Where should high-margin products be placed?", opts: [{text: "Near the entrance", isCorrect: false}, {text: "At eye level", isCorrect: true}, {text: "On the bottom shelf", isCorrect: false}, {text: "Near the register", isCorrect: false}], exp: "Eye-level is buy-level — high-margin products should be placed at eye height."}]],
    ["Handling Returns and Exchanges", "Navigate return policies while maintaining customer satisfaction.", ["returns", "exchanges", "customer service"], "beginner", 4, ["Return handling best practices:\n\n1. Greet the customer warmly — don't make them feel guilty\n2. Ask for the receipt and reason (for data, not judgment)\n3. Follow store policy but use good judgment\n4. Offer exchanges before refunds when appropriate\n5. Process quickly and efficiently\n6. Thank them for their business\n\nRemember: A well-handled return creates a loyal customer."], [{q: "What should you offer before a refund when appropriate?", opts: [{text: "Store credit only", isCorrect: false}, {text: "An exchange", isCorrect: true}, {text: "A discount on next purchase", isCorrect: false}, {text: "Nothing", isCorrect: false}], exp: "Offering an exchange before a refund can retain the sale while satisfying the customer."}]],
    ["Hotel Check-In Excellence", "Deliver a seamless check-in experience that sets the tone for the guest's stay.", ["hotel", "check-in", "hospitality"], "beginner", 4, ["The check-in experience sets the tone for the entire stay:\n\n1. Make eye contact and smile before the guest reaches the desk\n2. Use the guest's name at least twice during the interaction\n3. Confirm reservation details efficiently\n4. Explain key amenities and services\n5. Offer room upgrades when available\n6. Provide clear directions to the room\n7. Ask if there's anything else they need"], [{q: "How many times should you use the guest's name during check-in?", opts: [{text: "Once", isCorrect: false}, {text: "At least twice", isCorrect: true}, {text: "Every sentence", isCorrect: false}, {text: "Never", isCorrect: false}], exp: "Using the guest's name at least twice creates a personal connection."}]],
    ["Inventory Counting Best Practices", "Master cycle counting and full inventory procedures for accuracy.", ["inventory", "counting", "stock"], "intermediate", 5, ["Cycle counting vs. full inventory:\n\n• Cycle counting: Count a portion of inventory regularly (daily/weekly)\n• Full inventory: Count everything at once (quarterly/annually)\n\nBest practices:\n1. Count during low-traffic periods\n2. Use two-person teams (counter + recorder)\n3. Count items in the same direction consistently\n4. Investigate discrepancies immediately\n5. Update the system in real-time"], [{q: "What is cycle counting?", opts: [{text: "Counting everything at once", isCorrect: false}, {text: "Counting a portion of inventory regularly", isCorrect: true}, {text: "Counting only damaged items", isCorrect: false}, {text: "Counting items on sale", isCorrect: false}], exp: "Cycle counting involves counting a portion of inventory on a regular rotating basis."}]],
    ["Food Allergen Awareness", "Identify the 14 major allergens and prevent cross-contamination in food service.", ["allergens", "food safety", "cross-contamination"], "beginner", 5, ["The 14 major allergens:\n1. Celery  2. Cereals (gluten)  3. Crustaceans  4. Eggs  5. Fish  6. Lupin  7. Milk  8. Molluscs  9. Mustard  10. Nuts  11. Peanuts  12. Sesame  13. Soybeans  14. Sulphur dioxide\n\nPrevention: Use separate utensils, clean surfaces thoroughly, never guess — always check ingredients, and take every allergy report seriously."], [{q: "How should you respond when a customer reports a food allergy?", opts: [{text: "Tell them it's probably fine", isCorrect: false}, {text: "Take it seriously and check all ingredients", isCorrect: true}, {text: "Suggest they eat somewhere else", isCorrect: false}, {text: "Only worry about peanut allergies", isCorrect: false}], exp: "Always take every allergy report seriously and verify all ingredients."}]],
  ];

  for (const [title, desc, tags, diff, dur, texts, quizzes] of retailLessons) {
    lessons.push(makeLesson(title, desc, "Retail & Hospitality", "Retail", tags, diff, dur, texts, quizzes));
  }

  // ═══════════════════════════════════════════════════════════════════
  // MANUFACTURING & WAREHOUSING (35 lessons)
  // ═══════════════════════════════════════════════════════════════════

  const manufacturingLessons: Array<[string, string, string[], "beginner"|"intermediate"|"advanced", number, string[], Array<{q:string;opts:{text:string;isCorrect:boolean}[];exp:string}>]> = [
    ["Lockout/Tagout (LOTO) Procedures", "Understand OSHA lockout/tagout requirements to prevent hazardous energy release.", ["LOTO", "lockout", "tagout", "safety"], "intermediate", 5,
      ["Lockout/Tagout (LOTO) prevents the unexpected startup of machinery during maintenance. OSHA standard 29 CFR 1910.147.\n\nThe 6 Steps:\n1. Notify affected employees\n2. Shut down the equipment\n3. Isolate energy sources\n4. Apply lockout/tagout devices\n5. Release stored energy\n6. Verify isolation\n\nNEVER remove someone else's lock. Each worker applies their own lock."],
      [{q: "Can you remove another worker's lockout device?", opts: [{text: "Yes, if you're a supervisor", isCorrect: false}, {text: "Never", isCorrect: true}, {text: "Only in emergencies", isCorrect: false}, {text: "Yes, after their shift ends", isCorrect: false}], exp: "You should NEVER remove another worker's lockout device. Each worker is responsible for their own lock."}]],
    ["Confined Space Entry", "Learn the hazards and safety procedures for entering confined spaces.", ["confined space", "entry", "safety"], "advanced", 5,
      ["A confined space has: limited entry/exit, is not designed for continuous occupancy, and is large enough to enter. Hazards include:\n\n• Oxygen deficiency or enrichment\n• Toxic atmospheres\n• Engulfment\n• Entrapment\n\nRequired before entry:\n1. Atmospheric testing (O2, LEL, toxics)\n2. Entry permit signed by supervisor\n3. Attendant stationed outside\n4. Rescue plan in place\n5. Continuous ventilation"],
      [{q: "What must be done before entering a confined space?", opts: [{text: "Just wear a hard hat", isCorrect: false}, {text: "Atmospheric testing", isCorrect: true}, {text: "Nothing special", isCorrect: false}, {text: "Only notify your supervisor", isCorrect: false}], exp: "Atmospheric testing for oxygen levels, flammable gases, and toxic substances is required before confined space entry."}]],
    ["5S Workplace Organization", "Implement the 5S methodology to create an organized, efficient workspace.", ["5S", "lean", "organization"], "beginner", 4,
      ["5S is a lean manufacturing methodology:\n\n1. Sort (Seiri) — Remove unnecessary items\n2. Set in Order (Seiton) — Organize remaining items\n3. Shine (Seiso) — Clean the workspace\n4. Standardize (Seiketsu) — Create consistent procedures\n5. Sustain (Shitsuke) — Maintain the discipline\n\nBenefits: Reduced waste, improved safety, higher productivity, better morale."],
      [{q: "What is the first step in the 5S methodology?", opts: [{text: "Shine", isCorrect: false}, {text: "Sort", isCorrect: true}, {text: "Standardize", isCorrect: false}, {text: "Set in Order", isCorrect: false}], exp: "Sort (Seiri) is the first step — remove unnecessary items from the workspace."}]],
    ["Machine Guarding Safety", "Understand OSHA machine guarding requirements and hazard zones.", ["machine guarding", "safety", "OSHA"], "intermediate", 5, ["Machine guarding protects workers from hazards such as:\n• Point of operation — where work is performed\n• Power transmission — belts, gears, shafts\n• Nip points — where two parts move together\n• Rotating parts — flywheels, spindles\n\nGuard types: Fixed guards, interlocked guards, adjustable guards, self-adjusting guards. Never operate machinery with guards removed."], [{q: "What should you do if a machine guard is missing or damaged?", opts: [{text: "Continue working carefully", isCorrect: false}, {text: "Stop and report it immediately", isCorrect: true}, {text: "Fix it yourself", isCorrect: false}, {text: "Work around it", isCorrect: false}], exp: "Never operate machinery with missing or damaged guards. Stop and report immediately."}]],
    ["Forklift Pre-Operation Inspection", "Complete a thorough pre-operation inspection before operating a forklift.", ["forklift", "inspection", "safety"], "beginner", 4, ["Before operating a forklift, inspect:\n\n• Tires — check for damage and proper inflation\n• Forks — check for cracks, bends, and wear\n• Mast — check chains, rollers, and cylinders\n• Fluids — oil, hydraulic fluid, coolant, fuel\n• Brakes — test service and parking brakes\n• Lights and horn — ensure all are functional\n• Seat belt — must be worn at all times\n\nDocument all findings on the inspection checklist. Do NOT operate if defects are found."], [{q: "What should you do if you find a defect during pre-operation inspection?", opts: [{text: "Operate carefully", isCorrect: false}, {text: "Do NOT operate and report the defect", isCorrect: true}, {text: "Fix it yourself", isCorrect: false}, {text: "Use a different forklift without inspecting", isCorrect: false}], exp: "Never operate a forklift with known defects. Report and tag it out of service."}]],
    ["Lean Manufacturing: Eliminating Waste", "Identify and eliminate the 8 wastes of lean manufacturing.", ["lean", "waste", "efficiency"], "intermediate", 5, ["The 8 Wastes (DOWNTIME):\n\nD - Defects\nO - Overproduction\nW - Waiting\nN - Non-utilized talent\nT - Transportation\nI - Inventory excess\nM - Motion waste\nE - Extra processing\n\nStart by observing your work area for 30 minutes. You'll likely identify at least 3 types of waste that can be reduced."], [{q: "What does the 'N' in DOWNTIME stand for?", opts: [{text: "Negligence", isCorrect: false}, {text: "Non-utilized talent", isCorrect: true}, {text: "No inventory", isCorrect: false}, {text: "New processes", isCorrect: false}], exp: "N stands for Non-utilized talent — failing to use people's skills and knowledge."}]],
  ];

  for (const [title, desc, tags, diff, dur, texts, quizzes] of manufacturingLessons) {
    lessons.push(makeLesson(title, desc, "Manufacturing & Warehousing", "Manufacturing", tags, diff, dur, texts, quizzes));
  }

  // ═══════════════════════════════════════════════════════════════════
  // CONSTRUCTION & TRADES (30 lessons)
  // ═══════════════════════════════════════════════════════════════════

  const constructionLessons: Array<[string, string, string[], "beginner"|"intermediate"|"advanced", number, string[], Array<{q:string;opts:{text:string;isCorrect:boolean}[];exp:string}>]> = [
    ["Fall Protection: Harness Inspection", "Learn to inspect and properly wear a fall protection harness.", ["fall protection", "harness", "safety"], "intermediate", 5,
      ["Falls are the #1 cause of death in construction. OSHA requires fall protection at 6 feet in construction.\n\nHarness inspection checklist:\n• Webbing — check for cuts, fraying, burns, chemical damage\n• D-rings — check for cracks, distortion, corrosion\n• Buckles — ensure they lock and release properly\n• Labels — check manufacture date (max 5-year lifespan)\n• Stitching — look for pulled, cut, or broken threads\n\nAfter a fall, the harness MUST be removed from service."],
      [{q: "At what height does OSHA require fall protection in construction?", opts: [{text: "4 feet", isCorrect: false}, {text: "6 feet", isCorrect: true}, {text: "10 feet", isCorrect: false}, {text: "15 feet", isCorrect: false}], exp: "OSHA requires fall protection at 6 feet in construction (4 feet in general industry)."}]],
    ["Scaffolding Safety", "Understand scaffold types, inspection requirements, and safe use practices.", ["scaffolding", "safety", "construction"], "intermediate", 5, ["Scaffold safety essentials:\n\n• Must support 4x its maximum intended load\n• Planking must be scaffold-grade and extend 6-12 inches past supports\n• Guardrails required at 10+ feet: top rail (42\"), mid rail (21\"), toeboard (4\")\n• Never use ladders on scaffolds\n• Inspect before each shift\n• Only competent persons can erect/dismantle scaffolds"], [{q: "What load must scaffolding support?", opts: [{text: "2x maximum intended load", isCorrect: false}, {text: "4x maximum intended load", isCorrect: true}, {text: "Equal to maximum intended load", isCorrect: false}, {text: "3x maximum intended load", isCorrect: false}], exp: "Scaffolding must be able to support 4 times its maximum intended load."}]],
    ["Excavation & Trenching Safety", "Learn the hazards and protective systems for excavation work.", ["excavation", "trenching", "safety"], "advanced", 5, ["Trenching is one of the most hazardous construction operations. A cubic yard of soil weighs 3,000+ pounds.\n\nProtective systems required at 5+ feet depth:\n• Sloping — cutting the sides at an angle\n• Benching — creating steps in the sides\n• Shoring — installing supports\n• Shielding — using trench boxes\n\nA competent person must inspect the excavation daily and after every rainstorm."], [{q: "At what depth are protective systems required for trenches?", opts: [{text: "3 feet", isCorrect: false}, {text: "5 feet", isCorrect: true}, {text: "10 feet", isCorrect: false}, {text: "Any depth", isCorrect: false}], exp: "OSHA requires protective systems for trenches 5 feet or deeper."}]],
    ["Electrical Safety on Job Sites", "Understand electrical hazards and safe work practices on construction sites.", ["electrical", "safety", "GFCI"], "intermediate", 4, ["Electrocution is one of the OSHA 'Fatal Four' in construction.\n\nKey safety measures:\n• Use GFCI protection on all temporary wiring\n• Inspect cords and tools before each use\n• Keep 10+ feet from overhead power lines\n• Never use damaged cords or tools\n• Assume all wires are energized until verified\n• Use non-conductive ladders near electrical sources"], [{q: "What is the minimum safe distance from overhead power lines?", opts: [{text: "5 feet", isCorrect: false}, {text: "10 feet", isCorrect: true}, {text: "15 feet", isCorrect: false}, {text: "20 feet", isCorrect: false}], exp: "Maintain at least 10 feet from overhead power lines."}]],
    ["Heat Illness Prevention", "Recognize and prevent heat-related illnesses on outdoor job sites.", ["heat", "illness", "prevention", "outdoor"], "beginner", 4, ["Heat illness progresses through stages:\n\n1. Heat cramps — muscle cramps, sweating\n2. Heat exhaustion — heavy sweating, weakness, nausea, dizziness\n3. Heat stroke — HIGH BODY TEMP, confusion, loss of consciousness (EMERGENCY)\n\nPrevention: Water, Rest, Shade\n• Drink water every 15-20 minutes\n• Take breaks in shade\n• Acclimatize new workers gradually (start with 20% workload)\n• Use buddy system to watch for symptoms"], [{q: "What are the three key prevention measures for heat illness?", opts: [{text: "Medicine, rest, shade", isCorrect: false}, {text: "Water, rest, shade", isCorrect: true}, {text: "Water, food, shade", isCorrect: false}, {text: "Water, rest, sunscreen", isCorrect: false}], exp: "The three key prevention measures are Water, Rest, and Shade."}]],
  ];

  for (const [title, desc, tags, diff, dur, texts, quizzes] of constructionLessons) {
    lessons.push(makeLesson(title, desc, "Construction & Trades", "Construction", tags, diff, dur, texts, quizzes));
  }

  // ═══════════════════════════════════════════════════════════════════
  // TRANSPORTATION & LOGISTICS (30 lessons)
  // ═══════════════════════════════════════════════════════════════════

  const transportLessons: Array<[string, string, string[], "beginner"|"intermediate"|"advanced", number, string[], Array<{q:string;opts:{text:string;isCorrect:boolean}[];exp:string}>]> = [
    ["Pre-Trip Vehicle Inspection", "Complete a thorough pre-trip inspection to ensure vehicle safety.", ["pre-trip", "inspection", "vehicle"], "beginner", 5,
      ["A proper pre-trip inspection covers:\n\n• Engine compartment: oil, coolant, belts, hoses\n• Cab: mirrors, gauges, controls, seat belt\n• Exterior: tires (tread depth, pressure), lights, reflectors\n• Coupling devices: fifth wheel, kingpin, glad hands\n• Brakes: air pressure, brake adjustment, parking brake\n• Cargo: securement, weight distribution, doors\n\nDocument all findings. Never operate with critical defects."],
      [{q: "What should you check first during a pre-trip inspection?", opts: [{text: "Cargo", isCorrect: false}, {text: "Engine compartment", isCorrect: true}, {text: "Tires only", isCorrect: false}, {text: "Mirrors", isCorrect: false}], exp: "Start with the engine compartment to check fluid levels, belts, and hoses."}]],
    ["Hours of Service (HOS) Regulations", "Understand FMCSA hours of service rules for commercial drivers.", ["HOS", "regulations", "FMCSA", "driving"], "intermediate", 5, ["Key HOS rules for property-carrying drivers:\n\n• 11-Hour Driving Limit: Max 11 hours after 10 consecutive hours off duty\n• 14-Hour Window: Cannot drive after 14 hours on duty\n• 30-Minute Break: Required after 8 cumulative hours of driving\n• 60/70-Hour Limit: Cannot drive after 60/70 hours on duty in 7/8 days\n• Restart: 34 consecutive hours off duty resets the 60/70-hour clock\n\nELD (Electronic Logging Device) is mandatory for recording HOS."], [{q: "How many hours can a property-carrying driver drive after 10 hours off?", opts: [{text: "8 hours", isCorrect: false}, {text: "11 hours", isCorrect: true}, {text: "14 hours", isCorrect: false}, {text: "10 hours", isCorrect: false}], exp: "The 11-Hour Driving Limit allows up to 11 hours of driving after 10 consecutive hours off duty."}]],
    ["Defensive Driving Techniques", "Apply defensive driving strategies to prevent accidents on the road.", ["defensive driving", "safety", "awareness"], "beginner", 4, ["The SMITH System for defensive driving:\n\n1. Aim High in Steering — look 15 seconds ahead\n2. Get the Big Picture — scan the entire scene\n3. Keep Your Eyes Moving — check mirrors every 5-8 seconds\n4. Leave Yourself an Out — maintain space cushion\n5. Make Sure They See You — use signals, lights, horn\n\nThe 4-second following rule: Maintain at least 4 seconds of following distance (increase in bad weather)."], [{q: "What is the recommended following distance in normal conditions?", opts: [{text: "2 seconds", isCorrect: false}, {text: "4 seconds", isCorrect: true}, {text: "6 seconds", isCorrect: false}, {text: "1 second", isCorrect: false}], exp: "Maintain at least 4 seconds of following distance in normal conditions."}]],
    ["Cargo Securement Basics", "Learn proper cargo securement methods to prevent load shifts and spills.", ["cargo", "securement", "load"], "intermediate", 5, ["FMCSA cargo securement rules:\n\n• Cargo must be immobilized or secured\n• Minimum tiedown requirements based on cargo weight\n• Inspect securement within first 50 miles, then every 150 miles or 3 hours\n• Working load limit (WLL) of tiedowns must equal at least 50% of cargo weight\n\nCommon methods: Straps, chains, binders, blocking, bracing, friction mats."], [{q: "When should you first inspect cargo securement after departure?", opts: [{text: "After 100 miles", isCorrect: false}, {text: "Within the first 50 miles", isCorrect: true}, {text: "After 200 miles", isCorrect: false}, {text: "Only at destination", isCorrect: false}], exp: "Inspect cargo securement within the first 50 miles of departure."}]],
    ["Hazmat Transportation Awareness", "Understand hazmat classification, placarding, and emergency procedures.", ["hazmat", "transportation", "placards"], "advanced", 5, ["DOT Hazmat Classes:\n1. Explosives\n2. Gases\n3. Flammable liquids\n4. Flammable solids\n5. Oxidizers\n6. Poisons/Toxic\n7. Radioactive\n8. Corrosives\n9. Miscellaneous\n\nPlacarding required when shipping 1,001+ lbs of a single hazmat class. Shipping papers must be within reach of the driver at all times."], [{q: "When is hazmat placarding required?", opts: [{text: "For any amount", isCorrect: false}, {text: "Over 1,001 lbs of a single class", isCorrect: true}, {text: "Only for Class 1", isCorrect: false}, {text: "Over 5,000 lbs", isCorrect: false}], exp: "Placarding is required when shipping 1,001 pounds or more of a single hazmat class."}]],
  ];

  for (const [title, desc, tags, diff, dur, texts, quizzes] of transportLessons) {
    lessons.push(makeLesson(title, desc, "Transportation & Logistics", "Transportation", tags, diff, dur, texts, quizzes));
  }

  // ═══════════════════════════════════════════════════════════════════
  // FOOD SERVICE & RESTAURANT (30 lessons)
  // ═══════════════════════════════════════════════════════════════════

  const foodServiceLessons: Array<[string, string, string[], "beginner"|"intermediate"|"advanced", number, string[], Array<{q:string;opts:{text:string;isCorrect:boolean}[];exp:string}>]> = [
    ["Food Temperature Danger Zone", "Understand the temperature danger zone and proper food storage temperatures.", ["temperature", "food safety", "danger zone"], "beginner", 4,
      ["The Temperature Danger Zone: 41°F - 135°F (5°C - 57°C)\n\nBacteria multiply rapidly in this range. The 2-Hour Rule: Discard food left in the danger zone for more than 2 hours (1 hour if above 90°F).\n\nSafe temperatures:\n• Cold holding: 41°F (5°C) or below\n• Hot holding: 135°F (57°C) or above\n• Cooking: varies by food (165°F for poultry, 155°F for ground meat, 145°F for fish)\n• Reheating: 165°F (74°C) within 2 hours"],
      [{q: "What is the temperature danger zone?", opts: [{text: "32°F - 100°F", isCorrect: false}, {text: "41°F - 135°F", isCorrect: true}, {text: "50°F - 150°F", isCorrect: false}, {text: "0°F - 200°F", isCorrect: false}], exp: "The danger zone is 41°F to 135°F where bacteria multiply most rapidly."}]],
    ["FIFO: First In, First Out", "Master the FIFO method for proper food rotation and waste reduction.", ["FIFO", "food rotation", "inventory"], "beginner", 3, ["FIFO ensures older products are used first:\n\n1. Date-label all received items\n2. Place new items behind older items\n3. Check dates before using any product\n4. Discard items past their use-by date\n5. Never mix old and new products\n\nBenefits: Reduces waste, prevents serving expired food, maintains quality, saves money."], [{q: "Where should new inventory be placed?", opts: [{text: "In front of older items", isCorrect: false}, {text: "Behind older items", isCorrect: true}, {text: "On a separate shelf", isCorrect: false}, {text: "Wherever there's space", isCorrect: false}], exp: "New items go behind older items so older products are used first."}]],
    ["Knife Safety and Maintenance", "Learn proper knife handling, cutting techniques, and maintenance.", ["knife", "safety", "cutting"], "beginner", 4, ["Knife safety rules:\n\n• A sharp knife is safer than a dull one\n• Cut away from your body\n• Use the right knife for the task\n• Never catch a falling knife — step back\n• Carry knives at your side, point down\n• Never leave knives in soapy water\n• Use a cutting board — never cut in your hand\n\nMaintenance: Hone before each use, sharpen regularly, hand wash and dry immediately."], [{q: "What should you do if a knife is falling?", opts: [{text: "Try to catch it", isCorrect: false}, {text: "Step back and let it fall", isCorrect: true}, {text: "Grab the handle", isCorrect: false}, {text: "Use your foot to stop it", isCorrect: false}], exp: "Never try to catch a falling knife. Step back and let it fall."}]],
    ["ServSafe: Cross-Contamination Prevention", "Prevent cross-contamination through proper food handling and storage.", ["cross-contamination", "food safety", "ServSafe"], "intermediate", 5, ["Cross-contamination occurs when harmful organisms transfer from one surface to another.\n\nPrevention:\n• Separate raw and ready-to-eat foods\n• Store raw meats on bottom shelves (poultry lowest)\n• Use color-coded cutting boards\n• Change gloves between tasks\n• Sanitize surfaces between different food types\n• Never use the same utensils for raw and cooked food\n\nStorage order (top to bottom): Ready-to-eat, seafood, whole cuts of meat, ground meat, poultry"], [{q: "Where should raw poultry be stored in a refrigerator?", opts: [{text: "Top shelf", isCorrect: false}, {text: "Middle shelf", isCorrect: false}, {text: "Bottom shelf", isCorrect: true}, {text: "Anywhere is fine", isCorrect: false}], exp: "Raw poultry should be stored on the bottom shelf to prevent dripping onto other foods."}]],
    ["Proper Handwashing Technique", "Master the FDA-recommended handwashing procedure for food handlers.", ["handwashing", "hygiene", "food safety"], "beginner", 3, ["When to wash hands:\n• Before starting work\n• After using the restroom\n• After touching raw meat/poultry/fish\n• After sneezing, coughing, or touching face\n• After handling garbage\n• After handling money\n• When switching tasks\n\nThe 20-second procedure:\n1. Wet hands with warm water (100°F)\n2. Apply soap\n3. Scrub for 20 seconds (palms, backs, between fingers, under nails)\n4. Rinse thoroughly\n5. Dry with single-use towel\n6. Use towel to turn off faucet"], [{q: "How long should you scrub your hands when washing?", opts: [{text: "5 seconds", isCorrect: false}, {text: "10 seconds", isCorrect: false}, {text: "20 seconds", isCorrect: true}, {text: "60 seconds", isCorrect: false}], exp: "Scrub hands for at least 20 seconds with soap."}]],
  ];

  for (const [title, desc, tags, diff, dur, texts, quizzes] of foodServiceLessons) {
    lessons.push(makeLesson(title, desc, "Food Service & Restaurant", "Food Service", tags, diff, dur, texts, quizzes));
  }

  // ═══════════════════════════════════════════════════════════════════
  // SECURITY & LAW ENFORCEMENT (25 lessons)
  // ═══════════════════════════════════════════════════════════════════

  const securityLessons: Array<[string, string, string[], "beginner"|"intermediate"|"advanced", number, string[], Array<{q:string;opts:{text:string;isCorrect:boolean}[];exp:string}>]> = [
    ["Situational Awareness for Security", "Develop the observation skills needed for effective security work.", ["awareness", "observation", "security"], "beginner", 4,
      ["Cooper's Color Code of Awareness:\n\n• White — Unaware (dangerous)\n• Yellow — Relaxed alert (baseline for security)\n• Orange — Specific alert (something has caught your attention)\n• Red — High alert (threat confirmed, action required)\n\nSecurity professionals should operate in Yellow at minimum. Scan for: unusual behavior, items out of place, people who don't belong, and environmental changes."],
      [{q: "What is the baseline awareness level for security professionals?", opts: [{text: "White", isCorrect: false}, {text: "Yellow", isCorrect: true}, {text: "Orange", isCorrect: false}, {text: "Red", isCorrect: false}], exp: "Yellow (relaxed alert) is the baseline awareness level for security professionals."}]],
    ["Report Writing for Security", "Write clear, accurate, and legally defensible security reports.", ["report writing", "documentation", "security"], "intermediate", 5, ["Effective security reports follow the 5 W's + H:\n\nWho — All persons involved\nWhat — What happened\nWhen — Date, time, duration\nWhere — Specific location\nWhy — Apparent cause or motive\nHow — How the incident occurred\n\nRules:\n• Write in first person, past tense\n• Be objective — facts only, no opinions\n• Use specific details (not 'a man' but 'a male, approximately 6 feet tall, wearing...')\n• Complete the report before end of shift"], [{q: "What tense should security reports be written in?", opts: [{text: "Present tense", isCorrect: false}, {text: "Past tense", isCorrect: true}, {text: "Future tense", isCorrect: false}, {text: "Any tense", isCorrect: false}], exp: "Security reports should be written in past tense as they document events that have already occurred."}]],
    ["Access Control Procedures", "Manage building access, visitor management, and credential verification.", ["access control", "visitor", "credentials"], "beginner", 4, ["Access control layers:\n\n1. Perimeter — fences, gates, barriers\n2. Building — doors, locks, card readers\n3. Interior — restricted areas, server rooms\n4. Information — passwords, clearances\n\nVisitor management:\n• Verify identity with government-issued ID\n• Log entry time, purpose, and host\n• Issue temporary badge\n• Escort to destination if required\n• Log departure time and collect badge"], [{q: "What should you collect from visitors when they leave?", opts: [{text: "Their car keys", isCorrect: false}, {text: "Their temporary badge", isCorrect: true}, {text: "Their phone number", isCorrect: false}, {text: "Nothing", isCorrect: false}], exp: "Always collect the temporary badge when visitors depart."}]],
    ["De-escalation Techniques", "Learn verbal and non-verbal techniques to de-escalate confrontational situations.", ["de-escalation", "conflict", "communication"], "intermediate", 5, ["The LEAPS model for de-escalation:\n\nL — Listen actively\nE — Empathize with the person\nA — Ask questions to understand\nP — Paraphrase to show understanding\nS — Summarize and offer solutions\n\nBody language:\n• Maintain open posture\n• Keep hands visible\n• Maintain safe distance (arm's length +)\n• Speak slowly and calmly\n• Never point or cross arms"], [{q: "What does the 'E' in LEAPS stand for?", opts: [{text: "Evaluate", isCorrect: false}, {text: "Empathize", isCorrect: true}, {text: "Enforce", isCorrect: false}, {text: "Explain", isCorrect: false}], exp: "E stands for Empathize — showing you understand the person's feelings."}]],
  ];

  for (const [title, desc, tags, diff, dur, texts, quizzes] of securityLessons) {
    lessons.push(makeLesson(title, desc, "Security & Law Enforcement", "Security", tags, diff, dur, texts, quizzes));
  }

  // ═══════════════════════════════════════════════════════════════════
  // ENERGY & UTILITIES (20 lessons)
  // ═══════════════════════════════════════════════════════════════════

  const energyLessons: Array<[string, string, string[], "beginner"|"intermediate"|"advanced", number, string[], Array<{q:string;opts:{text:string;isCorrect:boolean}[];exp:string}>]> = [
    ["Arc Flash Safety", "Understand arc flash hazards and required protective measures.", ["arc flash", "electrical", "safety"], "advanced", 5,
      ["An arc flash is an explosive release of energy caused by an electrical fault. Temperatures can reach 35,000°F — four times the surface of the sun.\n\nNFPA 70E requirements:\n• Conduct arc flash risk assessment\n• Label all equipment with incident energy\n• Use appropriate PPE based on hazard level\n• Maintain safe approach boundaries\n• Only qualified workers may work on energized equipment\n\nBoundaries: Flash Protection Boundary, Limited Approach, Restricted Approach, Prohibited Approach"],
      [{q: "What temperature can an arc flash reach?", opts: [{text: "1,000°F", isCorrect: false}, {text: "5,000°F", isCorrect: false}, {text: "35,000°F", isCorrect: true}, {text: "100°F", isCorrect: false}], exp: "Arc flash temperatures can reach 35,000°F — four times the surface temperature of the sun."}]],
    ["Gas Leak Detection and Response", "Learn to detect, report, and respond to natural gas leaks safely.", ["gas leak", "detection", "safety"], "intermediate", 4, ["Signs of a gas leak:\n• Rotten egg smell (mercaptan odorant)\n• Hissing or blowing sound\n• Dead vegetation in a line\n• Bubbling in standing water\n• Dirt blowing from a hole\n\nResponse:\n1. Do NOT create sparks (no switches, phones, vehicles)\n2. Leave the area immediately\n3. Move upwind\n4. Call 911 and the gas company from a safe distance\n5. Do NOT re-enter until cleared by professionals"], [{q: "What should you NOT do if you suspect a gas leak?", opts: [{text: "Leave the area", isCorrect: false}, {text: "Call 911", isCorrect: false}, {text: "Flip light switches", isCorrect: true}, {text: "Move upwind", isCorrect: false}], exp: "Never create sparks near a gas leak — do not flip switches, use phones, or start vehicles."}]],
    ["Solar Panel Safety", "Understand the unique hazards of working with photovoltaic systems.", ["solar", "photovoltaic", "safety"], "intermediate", 5, ["Solar panel hazards:\n\n• Electrical shock — panels produce DC electricity whenever exposed to light\n• Falls — roof-mounted systems require fall protection\n• Burns — panels and inverters can be hot\n• Arc flash — DC arc flash at combiner boxes\n\nKey safety measures:\n• Cannot be fully de-energized during daylight\n• Use opaque covers to reduce output\n• Wear appropriate PPE (insulated gloves, arc-rated clothing)\n• Follow NFPA 70E for electrical safety"], [{q: "Can solar panels be fully de-energized during daylight?", opts: [{text: "Yes, with a switch", isCorrect: false}, {text: "No, they produce electricity whenever exposed to light", isCorrect: true}, {text: "Yes, by disconnecting the inverter", isCorrect: false}, {text: "Only on cloudy days", isCorrect: false}], exp: "Solar panels cannot be fully de-energized during daylight as they produce electricity whenever exposed to light."}]],
  ];

  for (const [title, desc, tags, diff, dur, texts, quizzes] of energyLessons) {
    lessons.push(makeLesson(title, desc, "Energy & Utilities", "Energy", tags, diff, dur, texts, quizzes));
  }

  // ═══════════════════════════════════════════════════════════════════
  // EDUCATION & CHILDCARE (20 lessons)
  // ═══════════════════════════════════════════════════════════════════

  const educationLessons: Array<[string, string, string[], "beginner"|"intermediate"|"advanced", number, string[], Array<{q:string;opts:{text:string;isCorrect:boolean}[];exp:string}>]> = [
    ["Mandatory Reporting: Child Abuse", "Understand your legal obligation as a mandatory reporter of child abuse.", ["mandatory reporting", "child abuse", "legal"], "intermediate", 5,
      ["As an educator or childcare worker, you are a mandatory reporter. This means you are legally required to report suspected child abuse or neglect.\n\nSigns to watch for:\n• Unexplained injuries or bruises\n• Sudden changes in behavior\n• Fear of going home\n• Poor hygiene or inappropriate clothing\n• Age-inappropriate sexual knowledge\n\nYour role: Report, don't investigate. Contact your local child protective services or law enforcement. You are protected from liability when reporting in good faith."],
      [{q: "As a mandatory reporter, what should you do when you suspect abuse?", opts: [{text: "Investigate first", isCorrect: false}, {text: "Report to authorities", isCorrect: true}, {text: "Confront the parents", isCorrect: false}, {text: "Wait for more evidence", isCorrect: false}], exp: "Your role is to report, not investigate. Contact child protective services or law enforcement."}]],
    ["Classroom Behavior Management", "Apply positive behavior strategies to create a productive learning environment.", ["behavior", "classroom", "management"], "intermediate", 4, ["Positive behavior strategies:\n\n1. Establish clear expectations from day one\n2. Use positive reinforcement (4:1 ratio of positive to corrective)\n3. Redirect before escalating\n4. Give choices, not ultimatums\n5. Use proximity — move closer to off-task students\n6. Maintain consistent consequences\n7. Build relationships — know your students\n\nThe key principle: Behavior is communication. Ask 'What is this child trying to tell me?'"], [{q: "What is the recommended ratio of positive to corrective feedback?", opts: [{text: "1:1", isCorrect: false}, {text: "2:1", isCorrect: false}, {text: "4:1", isCorrect: true}, {text: "10:1", isCorrect: false}], exp: "Research supports a 4:1 ratio of positive to corrective interactions."}]],
    ["First Aid for Children", "Learn age-appropriate first aid techniques for common childhood emergencies.", ["first aid", "children", "emergency"], "beginner", 5, ["Key differences in pediatric first aid:\n\n• CPR: 30:2 ratio (single rescuer), 15:2 (two rescuers)\n• Choking: Back blows + chest thrusts for infants, abdominal thrusts for children 1+\n• Fever: 100.4°F (38°C) or higher is a fever. Cool compresses, not cold baths.\n• Allergic reactions: Know which children have EpiPens and where they're stored\n• Head injuries: Monitor for 24 hours, watch for vomiting, confusion, unequal pupils\n\nAlways notify parents/guardians of any injury or illness."], [{q: "What temperature constitutes a fever in children?", opts: [{text: "98.6°F", isCorrect: false}, {text: "99°F", isCorrect: false}, {text: "100.4°F or higher", isCorrect: true}, {text: "102°F", isCorrect: false}], exp: "A temperature of 100.4°F (38°C) or higher is considered a fever."}]],
  ];

  for (const [title, desc, tags, diff, dur, texts, quizzes] of educationLessons) {
    lessons.push(makeLesson(title, desc, "Education & Childcare", "Education", tags, diff, dur, texts, quizzes));
  }

  // ═══════════════════════════════════════════════════════════════════
  // CLEANING & FACILITIES (20 lessons)
  // ═══════════════════════════════════════════════════════════════════

  const cleaningLessons: Array<[string, string, string[], "beginner"|"intermediate"|"advanced", number, string[], Array<{q:string;opts:{text:string;isCorrect:boolean}[];exp:string}>]> = [
    ["Chemical Safety: Reading SDS", "Learn to read Safety Data Sheets for cleaning chemicals.", ["SDS", "chemicals", "safety"], "beginner", 4,
      ["Safety Data Sheets (SDS) have 16 sections. The most critical for daily use:\n\nSection 2: Hazard identification — pictograms and signal words\nSection 4: First aid measures\nSection 7: Handling and storage\nSection 8: PPE requirements\n\nNever mix chemicals (especially bleach + ammonia = toxic chloramine gas). Always read the SDS before using a new product. SDS must be accessible to all employees at all times."],
      [{q: "What happens when you mix bleach and ammonia?", opts: [{text: "Nothing dangerous", isCorrect: false}, {text: "Toxic chloramine gas", isCorrect: true}, {text: "A better cleaner", isCorrect: false}, {text: "Foam", isCorrect: false}], exp: "Mixing bleach and ammonia produces toxic chloramine gas, which can cause serious respiratory harm."}]],
    ["Bloodborne Pathogen Cleanup", "Follow proper procedures for cleaning up blood and body fluid spills.", ["bloodborne", "pathogen", "cleanup"], "intermediate", 5, ["OSHA Bloodborne Pathogen Standard (29 CFR 1910.1030):\n\nCleanup procedure:\n1. Put on PPE (gloves, eye protection, gown if splash risk)\n2. Contain the spill with absorbent material\n3. Clean with EPA-registered disinfectant or 1:10 bleach solution\n4. Allow 10-minute contact time\n5. Dispose of waste in biohazard bag\n6. Remove PPE and wash hands\n\nTreat ALL blood and body fluids as potentially infectious."], [{q: "What concentration of bleach solution is used for bloodborne pathogen cleanup?", opts: [{text: "1:100", isCorrect: false}, {text: "1:10", isCorrect: true}, {text: "1:1", isCorrect: false}, {text: "Full strength", isCorrect: false}], exp: "A 1:10 bleach solution (1 part bleach to 10 parts water) is standard for bloodborne pathogen cleanup."}]],
    ["Floor Care: Slip and Fall Prevention", "Learn proper mopping, waxing, and signage techniques to prevent slips.", ["floor care", "slip prevention", "safety"], "beginner", 4, ["Slip and fall prevention:\n\n• Always use wet floor signs — place BEFORE mopping\n• Mop in sections, keeping one side dry for foot traffic\n• Use the figure-8 mopping pattern for efficiency\n• Change mop water frequently\n• Allow adequate drying time\n• Use non-slip floor finish\n• Clean up spills immediately\n\nLiability: Failure to post wet floor signs is the #1 cause of slip-and-fall lawsuits against facilities."], [{q: "When should wet floor signs be placed?", opts: [{text: "After mopping", isCorrect: false}, {text: "Before mopping", isCorrect: true}, {text: "Only when the floor is very wet", isCorrect: false}, {text: "Only in high-traffic areas", isCorrect: false}], exp: "Wet floor signs must be placed BEFORE mopping begins."}]],
  ];

  for (const [title, desc, tags, diff, dur, texts, quizzes] of cleaningLessons) {
    lessons.push(makeLesson(title, desc, "Cleaning & Facilities", "Cleaning", tags, diff, dur, texts, quizzes));
  }

  // ═══════════════════════════════════════════════════════════════════
  // GENERAL WORKPLACE SKILLS (50+ lessons)
  // ═══════════════════════════════════════════════════════════════════

  const generalLessons: Array<[string, string, string[], "beginner"|"intermediate"|"advanced", number, string[], Array<{q:string;opts:{text:string;isCorrect:boolean}[];exp:string}>]> = [
    ["Workplace Harassment Prevention", "Understand what constitutes harassment and how to report it.", ["harassment", "prevention", "workplace"], "beginner", 5,
      ["Workplace harassment includes unwelcome conduct based on race, color, religion, sex, national origin, age, disability, or genetic information.\n\nTypes:\n• Quid pro quo — 'this for that' (usually by supervisors)\n• Hostile work environment — severe or pervasive conduct\n\nIf you experience or witness harassment:\n1. Tell the person to stop (if safe)\n2. Document incidents (dates, times, witnesses)\n3. Report to HR or management\n4. You are protected from retaliation"],
      [{q: "What are you protected from when reporting harassment?", opts: [{text: "Nothing", isCorrect: false}, {text: "Retaliation", isCorrect: true}, {text: "Investigation", isCorrect: false}, {text: "Questioning", isCorrect: false}], exp: "You are legally protected from retaliation when reporting harassment in good faith."}]],
    ["Effective Shift Handoffs", "Master the art of communicating critical information during shift changes.", ["handoff", "shift change", "communication"], "beginner", 4,
      ["A poor handoff can lead to errors, delays, and safety incidents. Use the I-PASS framework:\n\nI — Illness severity (stable, worsening, critical)\nP — Patient/situation summary\nA — Action list (what needs to be done)\nS — Situational awareness (what to watch for)\nS — Synthesis (receiver summarizes back)\n\nTips: Never rush a handoff. Use a standardized checklist. Allow questions. Document key items."],
      [{q: "What should the receiver do at the end of a handoff?", opts: [{text: "Just nod", isCorrect: false}, {text: "Summarize back what they heard", isCorrect: true}, {text: "Sign a form", isCorrect: false}, {text: "Nothing", isCorrect: false}], exp: "The receiver should summarize back (synthesis) to confirm understanding."}]],
    ["Workplace Ergonomics", "Set up your workstation to prevent repetitive strain injuries.", ["ergonomics", "workstation", "RSI"], "beginner", 4, ["Ergonomic workstation setup:\n\n• Monitor: Top of screen at eye level, arm's length away\n• Chair: Feet flat on floor, thighs parallel to floor\n• Keyboard: Elbows at 90°, wrists neutral\n• Mouse: Close to keyboard, same height\n• Take breaks: 20-20-20 rule (every 20 min, look 20 feet away for 20 seconds)\n• Stretch: Stand and stretch every 30-60 minutes"], [{q: "What is the 20-20-20 rule?", opts: [{text: "Work 20 hours, rest 20 hours, repeat 20 times", isCorrect: false}, {text: "Every 20 min, look 20 feet away for 20 seconds", isCorrect: true}, {text: "Take 20 breaks of 20 minutes each day", isCorrect: false}, {text: "Adjust your chair 20 times a day", isCorrect: false}], exp: "The 20-20-20 rule: Every 20 minutes, look at something 20 feet away for 20 seconds to reduce eye strain."}]],
    ["Email Etiquette for Professionals", "Write clear, professional emails that get results.", ["email", "communication", "professional"], "beginner", 3, ["Professional email guidelines:\n\n• Subject line: Clear and specific (not 'Hi' or 'Question')\n• Opening: Address by name, state purpose in first sentence\n• Body: One topic per email, use short paragraphs\n• Action items: Bold or bullet-point what you need\n• Closing: Include deadline if applicable\n• Proofread: Check for typos, tone, and attachments\n\nResponse time: Acknowledge within 24 hours, even if you need more time to fully respond."], [{q: "How quickly should you acknowledge a professional email?", opts: [{text: "Within 1 hour", isCorrect: false}, {text: "Within 24 hours", isCorrect: true}, {text: "Within 1 week", isCorrect: false}, {text: "Whenever convenient", isCorrect: false}], exp: "Acknowledge professional emails within 24 hours, even if you need more time for a full response."}]],
    ["Conflict Resolution in the Workplace", "Navigate workplace disagreements constructively.", ["conflict", "resolution", "workplace"], "intermediate", 5, ["The DESC model for conflict resolution:\n\nD — Describe the specific behavior\nE — Express how it affects you\nS — Specify what you'd like instead\nC — Consequences (positive outcomes of change)\n\nExample: 'When meetings start late (D), I feel my time isn't valued (E). Could we agree to start on time? (S) This would help us all be more productive (C).'\n\nKey principles: Focus on behavior, not personality. Use 'I' statements. Listen to understand, not to respond."], [{q: "What does the 'E' in DESC stand for?", opts: [{text: "Evaluate", isCorrect: false}, {text: "Express", isCorrect: true}, {text: "Enforce", isCorrect: false}, {text: "Eliminate", isCorrect: false}], exp: "E stands for Express — how the behavior affects you."}]],
    ["Time Management: The Eisenhower Matrix", "Prioritize tasks effectively using the urgent/important framework.", ["time management", "prioritization", "Eisenhower"], "beginner", 4, ["The Eisenhower Matrix divides tasks into 4 quadrants:\n\n1. Urgent + Important → DO immediately\n2. Not Urgent + Important → SCHEDULE it\n3. Urgent + Not Important → DELEGATE it\n4. Not Urgent + Not Important → ELIMINATE it\n\nMost people spend too much time in Quadrant 3 (urgent but not important). The goal is to spend more time in Quadrant 2 (important but not urgent) — this is where strategic work happens."], [{q: "Which quadrant should you spend the most time in?", opts: [{text: "Urgent + Important", isCorrect: false}, {text: "Not Urgent + Important", isCorrect: true}, {text: "Urgent + Not Important", isCorrect: false}, {text: "Not Urgent + Not Important", isCorrect: false}], exp: "Quadrant 2 (Not Urgent + Important) is where strategic, high-value work happens."}]],
    ["Active Listening Skills", "Develop the ability to truly hear and understand what others are saying.", ["listening", "communication", "skills"], "beginner", 3, ["Active listening techniques:\n\n1. Give full attention — put away devices\n2. Show you're listening — nod, maintain eye contact\n3. Provide feedback — 'What I'm hearing is...'\n4. Defer judgment — don't interrupt\n5. Respond appropriately — be honest and respectful\n\nThe 80/20 rule: Listen 80% of the time, speak 20%. Most people do the opposite."], [{q: "What is the recommended listen-to-speak ratio?", opts: [{text: "50/50", isCorrect: false}, {text: "80/20 (listen/speak)", isCorrect: true}, {text: "20/80 (listen/speak)", isCorrect: false}, {text: "70/30", isCorrect: false}], exp: "The 80/20 rule: Listen 80% of the time and speak 20%."}]],
    ["Giving and Receiving Feedback", "Master the art of constructive feedback in both directions.", ["feedback", "communication", "growth"], "intermediate", 4, ["Giving feedback — the SBI model:\n\nS — Situation: 'In yesterday's team meeting...'\nB — Behavior: '...you interrupted Sarah three times...'\nI — Impact: '...which made her hesitant to share ideas.'\n\nReceiving feedback:\n1. Listen without defending\n2. Ask clarifying questions\n3. Thank the person\n4. Reflect before responding\n5. Take action on valid points\n\nFeedback is a gift — it's how we grow."], [{q: "What does SBI stand for in the feedback model?", opts: [{text: "Specific, Brief, Important", isCorrect: false}, {text: "Situation, Behavior, Impact", isCorrect: true}, {text: "Start, Build, Improve", isCorrect: false}, {text: "See, Believe, Implement", isCorrect: false}], exp: "SBI stands for Situation, Behavior, Impact — a structured way to give specific feedback."}]],
    ["Workplace Diversity and Inclusion", "Foster an inclusive workplace that values diverse perspectives.", ["diversity", "inclusion", "workplace"], "beginner", 5, ["Inclusion goes beyond diversity:\n\n• Diversity is being invited to the party\n• Inclusion is being asked to dance\n• Belonging is dancing like nobody's watching\n\nPractical actions:\n1. Use inclusive language\n2. Acknowledge and challenge your biases\n3. Amplify underrepresented voices\n4. Be an active bystander against discrimination\n5. Celebrate cultural differences\n6. Create psychological safety for all team members"], [{q: "What is the difference between diversity and inclusion?", opts: [{text: "They're the same thing", isCorrect: false}, {text: "Diversity is representation; inclusion is participation", isCorrect: true}, {text: "Inclusion is a policy; diversity is a practice", isCorrect: false}, {text: "Diversity is optional; inclusion is required", isCorrect: false}], exp: "Diversity is about representation (who's in the room), while inclusion is about participation (who's heard and valued)."}]],
    ["Digital Security Basics", "Protect yourself and your organization from common cyber threats.", ["cybersecurity", "phishing", "passwords"], "beginner", 4, ["Top cyber threats for employees:\n\n1. Phishing emails — look for urgency, misspellings, suspicious links\n2. Weak passwords — use 12+ characters, mix types, never reuse\n3. Public Wi-Fi — never access work systems on public networks\n4. Social engineering — verify identity before sharing information\n5. USB devices — never plug in unknown devices\n\nIf you suspect a breach: Report immediately, don't try to fix it yourself, change passwords, and preserve evidence."], [{q: "What is the minimum recommended password length?", opts: [{text: "6 characters", isCorrect: false}, {text: "8 characters", isCorrect: false}, {text: "12+ characters", isCorrect: true}, {text: "4 characters", isCorrect: false}], exp: "Use passwords of 12 or more characters with a mix of types."}]],
  ];

  for (const [title, desc, tags, diff, dur, texts, quizzes] of generalLessons) {
    lessons.push(makeLesson(title, desc, "General Workplace Skills", "General", tags, diff, dur, texts, quizzes));
  }

  return lessons;
}
